name: Rustico

on: [pull_request, push]

jobs:
  Testing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building
      run: cargo build
    - name: Testing
      run: cargo test
